---
title: "Stats 790 project"
output: html_document
date: "2023-04-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(SemiPar)
library(quantreg)
```

```{r}
data("age.income", package = "SemiPar")
data <- age.income
head(data)
par(mar = c(4, 4, 0.5, 0.5))
plot(log.income ~ age, data = age.income)
```

```{r}
rho <- function(u, tau = 0.5) {
  u*(tau-1*(u<0))
}

S <- function(u, tau = 0.5, alpha = 0.005) {
  tau*u+alpha*log(1+exp(-u/alpha))
}

```

```{r}
par(mar = c(4, 4, 0.5, 0.5))
curve(rho, -0.05, 0.05, col = 1, lwd = 1.5)
curve(S, -0.05, 0.05, col = 2, lwd = 1.5, add = TRUE)
legend(x = "top",legend = c("Differentiable","Non-differentiable"),lwd = c(1.5,1.5),col = c(2,1))
```


```{r}
qlm <- function(formula, data = NULL, tau = 0.5, alpha = 0.005,...)
{
  lm <- lm(formula, data = data)
  design_matrix <- model.matrix(lm)
  y <- model.response(model.frame(lm))
  objfun <- function(beta, tau) {
    eta <- design_matrix %*% beta
    sum(S(y - eta, tau, alpha))
  }
  beta <- list()
  tau <- sort(tau)
  start <- coef(lm)
  for(j in tau) {
    opt <- optim(start, fn = objfun, tau = j,
method = "BFGS", control = list(maxit = 1e+08))
    beta[[paste0(j * 100, "%")]] <- opt$par
    start <- opt$par
  }
  lm$coefficients <- do.call("cbind", beta)
  lm$call <- match.call()
  class(lm) <- c("qlm", "lm")
  return(lm)
}

predict.qlm <- function(object, newdata) {
  class(object) <- "lm"
  if(missing(newdata) || is.null(newdata)) {
    design_matrix <- model.matrix(object)
  } else {
    Terms <- delete.response(terms(object))
    m <- model.frame(Terms, newdata, xlev = object$xlevels)
    if(!is.null(cl <- attr(Terms, "dataClasses"))) 
      .checkMFClasses(cl, m)
    design_matrix <- model.matrix(Terms, m, contrasts.arg = object$contrasts)
  }

  l <- list()
  for(j in colnames(object$coefficients))
    l[[j]] <- design_matrix %*% object$coefficients[, j]
  l <- as.data.frame(l)
  names(l) <- colnames(object$coefficients)

  return(l)
}

tau <- c(0.05, 0.5, 0.95)
lm_2 <- qlm(log.income ~ poly(age, 4), data = age.income, tau = tau)
fit_1 <- predict.qlm(lm_2)

par(mar = c(4, 4, 0.5, 0.5))
plot(log.income ~ age, data = age.income)
matplot(age.income$age, fit_1, type = "l", lty = c(1, 2, 3), col = 1, lwd = 2, add = TRUE)
legend("topleft", paste0(tau*100, "%"), lwd = 2, lty = c(1, 2, 3), bty = "n")

```

```{r}
qr <- rq(log.income ~ poly(age, 5), data = age.income, tau = tau)
summary(qr)
fit_2 <- predict.qlm(qr)
par(mar = c(4, 4, 0.5, 0.5))
plot(log.income ~ age, data = age.income)
matplot(age.income$age, fit_1, type = "l", lty = c(1, 2, 3), col = 1, lwd = 2, add = TRUE)
matplot(age.income$age, fit_2, type = "l", lty = c(1, 2, 3), col = 2, lwd = 2, add = TRUE)
legend("topleft", paste0(tau*100, "%"), lwd = 2, lty = c(2, 1, 3), bty = "n")

tau <- c(0.05, 0.5, 0.95)
lm_3 <- qlm(log.income ~ poly(age, 5), data = age.income, tau = tau)
fit_3 <- predict.qlm(lm_3)
plot(log.income ~ age, data = age.income)
matplot(age.income$age, fit_3, type = "l", lty = c(1, 2, 3), col = 1, lwd = 2, add = TRUE)
matplot(age.income$age, fit_2, type = "l", lty = c(1, 2, 3), col = 2, lwd = 2, add = TRUE)
legend("topleft", paste0(tau*100, "%"), lwd = 2, lty = c(2, 1, 3), bty = "n")

```

```{r}
system.time(lm_2 <- qlm(log.income ~ poly(age, 4), data = age.income, tau = tau))
system.time(lm_3 <- qlm(log.income ~ poly(age, 5), data = age.income, tau = tau))
system.time(qr <- rq(log.income ~ poly(age, 5), data = age.income, tau = tau))
```

```{r}
mean((fit_1$`5%`-data$log.income)^2)
mean((fit_1$`50%`-data$log.income)^2)  ## quantile regression with degree 4 poly
mean((fit_1$`95%`-data$log.income)^2)

mean((fit_2$`tau= 0.05`-data$log.income)^2)
mean((fit_2$`tau= 0.50`-data$log.income)^2)  ##  build in quantile regression 
mean((fit_2$`tau= 0.95`-data$log.income)^2)

mean((fit_3$`5%`-data$log.income)^2)
mean((fit_3$`50%`-data$log.income)^2) ## quantile regression with degree 5 poly
mean((fit_3$`95%`-data$log.income)^2)
```
